#!/bin/sh
str="'$*'"
##directory where jar file is located    
dir=target
##jar file name
jar_name=co2-simulator-1.0-SNAPSHOT.jar

mvn clean install 

if [ -z "$1" ] ; then
        java -jar $dir/$jar_name
        exit 1

else
	java -jar $dir/$jar_name  "$str"

fi
